### ISSUE TITLE
conda not found

### ISSUE THREAD

**Issue by llllljm** [PabloMessina/MedVQA#2]
Hi! When I use pycharm to run the following code：
```
command = f"PYTHONPATH={}:$PYTHONPATH conda run -n dygiepp allennlp predict {model_path} {data_path} \
            --predictor dygie \
            --include-package dygie \
            --use-dataset-reader \
            --output-file {out_path} \
            --cuda-device {cuda} \
            --silent"

    print('Running command: ', command)

    ret = os.system(command)
```
it output "conda not found".Do you know why it happens?
Thanks

**Comment by PabloMessina** [comment]
Probably because conda is not installed. You need to install conda first. Here are the official installation instructions: https://docs.conda.io/projects/conda/en/latest/user-guide/install/index.html

Also take a look at the instructions here: https://github.com/PabloMessina/MedVQA/blob/master/medvqa/scripts/radgraph/radgraph_allennlp_inference.py#L1

You also will need to download the RadGraph dataset, in order to have access to the pre-trained model weights. See here: https://physionet.org/content/radgraph/1.0.0/

**Comment by llllljm** [comment]
Thank you for your reply!
I add the path of conda like this
`command = f"PYTHONPATH={}:$PYTHONPATH condaPath/conda run -n dygiepp allennlp predict {model_path} {data_path} \
            --predictor dygie \
            --include-package dygie \
            --use-dataset-reader \
            --output-file {out_path} \
            --cuda-device {cuda} \
            --silent"
`
Then the command successfully run.
